name: Upload SysY-compiler to xiji gitlab server

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download SysY-compiler artifact
        uses: actions/download-artifact@v3
        with:
          name: SysY-compiler-ubuntu-20.04-hfON

      - name: Unzip it
        run: unzip SysY-compiler-ubuntu-20.04-hfON.zip

      - name: Zip it to tar.gz format
        run: tar -zcvf sysy_compiler.tar.gz sysy_compiler

      - name: Clone SysY-compiler-loader repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.XIJI_REPO }}
          path: './loader'
          token: ${{ secrets.XIJI_PAT }}
          github-server-url: ${{ secrets.XIJI_SERVER }}

      - name: Upload SysY-compiler to xiji gitlab server
        run: |
          rm loader/sysy_compiler.tar.gz
          mv sysy_compiler.tar.gz loader
          cd loader
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sysy_compiler.tar.gz
          git commit -m "update sysy_compiler"
          git push